export type { Post } from './model/types'
export { postApi } from './api/postApi'
export { PostList } from './ui/post-list/PostList'
export { PostCard } from './ui/post-card/PostCard'
export { postSlice } from './model/postSlice'
